stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - digitalocean
  script:
    - echo "Building..."

test:
  stage: test
  tags:
    - digitalocean
  script:
    - echo "testing.."


deploy:
   stage: deploy
   tags:
    - digitalocean
   script:
    - echo "deploying..."