variables:
  GIT_STRATEGY: fetch
  GIT_CLEAN_FLAGS: none

stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - digitalocean
  script:
    - echo "Building..."
    - cp .env.example .env
    - composer install
    - php artisan key:generate
    - npm install
    - npm run build

test:
  stage: test
  tags:
    - digitalocean
  script:
    - echo "testing.."
    - php artisan test

deploy:
   stage: deploy
   tags:
    - digitalocean
   script:
    - echo "deploying.."