variables:
  GIT_STRATEGY: fetch
  GIT_CLEAN_FLAGS: none

stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - digitalocean
  script:
    - echo "Building..."
    - cp .env.example .env
    - composer install
    - php artisan key:generate
    - npm install
    - npm run build

test:
  stage: test
  tags:
    - digitalocean
  script:
    - echo "testing.."
    - php artisan test

deploy_staging:
   stage: deploy
   tags:
     - digitalocean
   script:
     - echo "deploying to staging enviroment"
    # - ssh deploy@staging_server_ip -o StrictHostKeyChecking=no 'bash /path/to/the/deploy _scripts'
   environment:
     name: staging

deploy_production:
   stage: deploy
   tags:
    - digitalocean
   script:
    - echo "deploying.."
    - ssh dare@165.22.235.232 -o StrictHostKeyChecking=no 'bash /var/www/larademo/scripts/deploy.sh'
   environment:
     name: prodcuction
   when: manual